// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbZY3zVLgBsidvGWMBwYa2olyewwC4nr8',
    appId: '1:407375604191:web:e38144156c98ef5bc0fc6a',
    messagingSenderId: '407375604191',
    projectId: 'medical-diagnosis-system-5ac77',
    authDomain: 'medical-diagnosis-system-5ac77.firebaseapp.com',
    storageBucket: 'medical-diagnosis-system-5ac77.appspot.com',
    measurementId: 'G-LRX2W6JZ8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHtCgBxVGgFT8t5Wdr1KCyTgEyHNpu8VA',
    appId: '1:407375604191:android:e0c11cff6a0ff2e1c0fc6a',
    messagingSenderId: '407375604191',
    projectId: 'medical-diagnosis-system-5ac77',
    storageBucket: 'medical-diagnosis-system-5ac77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYKFlwlGoU_LvTjatzuGOB4bhS2hJm9vg',
    appId: '1:407375604191:ios:afe7d4235b883851c0fc6a',
    messagingSenderId: '407375604191',
    projectId: 'medical-diagnosis-system-5ac77',
    storageBucket: 'medical-diagnosis-system-5ac77.appspot.com',
    iosBundleId: 'com.example.medicalDiagnosisSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYKFlwlGoU_LvTjatzuGOB4bhS2hJm9vg',
    appId: '1:407375604191:ios:9fd4d57cace450b0c0fc6a',
    messagingSenderId: '407375604191',
    projectId: 'medical-diagnosis-system-5ac77',
    storageBucket: 'medical-diagnosis-system-5ac77.appspot.com',
    iosBundleId: 'com.example.medicalDiagnosisSystem.RunnerTests',
  );
}
