// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAr5CqnvmZbNVVPoktUFL39Dbwlj15I1F0',
    appId: '1:430987198672:web:ffb4eb44c8394d2b515ed5',
    messagingSenderId: '430987198672',
    projectId: 'chat-app-219b0',
    authDomain: 'chat-app-219b0.firebaseapp.com',
    storageBucket: 'chat-app-219b0.appspot.com',
    measurementId: 'G-W7NPZ4334Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBK0eZ6PiXIMrK5zesTtI0gcq51xdxC--o',
    appId: '1:430987198672:android:6944f770692db2b3515ed5',
    messagingSenderId: '430987198672',
    projectId: 'chat-app-219b0',
    storageBucket: 'chat-app-219b0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATHlXdyTpI3tIYQVJaGiymQN3W_sQNV-A',
    appId: '1:430987198672:ios:8150d2945a0c8298515ed5',
    messagingSenderId: '430987198672',
    projectId: 'chat-app-219b0',
    storageBucket: 'chat-app-219b0.appspot.com',
    iosClientId: '430987198672-kr3doppff7dah8hq5n9ropn0e1qnko68.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalDiagnosisSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATHlXdyTpI3tIYQVJaGiymQN3W_sQNV-A',
    appId: '1:430987198672:ios:4804420eb7aff1c2515ed5',
    messagingSenderId: '430987198672',
    projectId: 'chat-app-219b0',
    storageBucket: 'chat-app-219b0.appspot.com',
    iosClientId: '430987198672-81s989t9vm6409uod60gek7qiqrkogc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicalDiagnosisSystem.RunnerTests',
  );
}
